region: ee-lte-1
domain: can-i-haz-kubernetes.ee-lte-1.codemowers.io

uploader:
  image: git.codemowers.io/matmlazi/lolcatz-foobar/uploader:latest
browse:
  image: git.codemowers.io/matmlazi/lolcatz-foobar/browse:latest
search:
  image: git.codemowers.io/matmlazi/lolcatz-foobar/search:latest
comments:
  image: git.codemowers.io/matmlazi/lolcatz-foobar/comments:latest
tagger:
  image: git.codemowers.io/matmlazi/lolcatz-foobar/tagger:latest
frontend:
  image: git.codemowers.io/matmlazi/lolcatz-foobar/frontend:latest
