---
when:
  branch: main
  event: push

variables:
  - &registry zot.ee-lte-1.codemowers.io/matmlazi/lolcatz-foobar

steps:
  build-uploader:
    image: gcr.io/kaniko-project/executor:latest
    settings:
      dockerfile: services/uploader/Dockerfile
      context: services/uploader
      destination: *registry/uploader:${CI_COMMIT_SHA:0:8}
    environment:
      DOCKER_CONFIG:
        from_secret: zot_docker_config

  build-browse:
    image: gcr.io/kaniko-project/executor:latest
    settings:
      dockerfile: services/browse/Dockerfile
      context: services/browse
      destination: *registry/browse:${CI_COMMIT_SHA:0:8}
    environment:
      DOCKER_CONFIG:
        from_secret: zot_docker_config

  build-search:
    image: gcr.io/kaniko-project/executor:latest
    settings:
      dockerfile: services/search/Dockerfile
      context: services/search
      destination: *registry/search:${CI_COMMIT_SHA:0:8}
    environment:
      DOCKER_CONFIG:
        from_secret: zot_docker_config

  build-comments:
    image: gcr.io/kaniko-project/executor:latest
    settings:
      dockerfile: services/comments/Dockerfile
      context: services/comments
      destination: *registry/comments:${CI_COMMIT_SHA:0:8}
    environment:
      DOCKER_CONFIG:
        from_secret: zot_docker_config

  build-tagger:
    image: gcr.io/kaniko-project/executor:latest
    settings:
      dockerfile: services/tagger/Dockerfile
      context: services/tagger
      destination: *registry/tagger:${CI_COMMIT_SHA:0:8}
    environment:
      DOCKER_CONFIG:
        from_secret: zot_docker_config

  build-tagger-model:
    image: gcr.io/kaniko-project/executor:latest
    settings:
      dockerfile: services/tagger/Dockerfile.model
      context: services/tagger
      destination: *registry/tagger-model:${CI_COMMIT_SHA:0:8}
    environment:
      DOCKER_CONFIG:
        from_secret: zot_docker_config

  build-frontend:
    image: gcr.io/kaniko-project/executor:latest
    settings:
      dockerfile: frontend/Dockerfile
      context: frontend
      destination: *registry/frontend:${CI_COMMIT_SHA:0:8}
    environment:
      DOCKER_CONFIG:
        from_secret: zot_docker_config
