events {}

http {
    server {
        listen 8080;

        location /api/admin/ {
            proxy_pass http://admin:8080;
        }

        location /api/browse/ {
            proxy_pass http://browse:8080;
        }

        location /api/thumbnails/ {
            proxy_pass http://thumbnailer:8080;
        }

        location /api/search/ {
            proxy_pass http://search:8080;
        }

        location /api/comments/ {
            proxy_pass http://comments:8080;
        }

        location /api/upload/ {
            client_max_body_size 100m;
            proxy_request_buffering off;
            proxy_pass http://uploader:8080;
        }

        location / {
            proxy_pass http://frontend:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
