apiVersion: secretgenerator.mittwald.de/v1alpha1
kind: StringSecret
metadata:
  name: lolcatz-redis-password
spec:
  forceRegenerate: false
  fields:
    - fieldName: password
      encoding: hex
      length: "32"
