"""HTTP fallback for existing uploads and thumbnails not yet generated by Kafka."""
import logging
from uuid import UUID

from botocore.exceptions import EndpointConnectionError, ConnectionClosedError, ReadTimeoutError, ConnectTimeoutError
from thumbnail import InvalidImage
from metrics import HTTPMetrics, FALLBACKS

from flask import Flask, abort, redirect, request

from cache import ThumbnailCache
from thumbnail import SIZES, VERSION

log = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO)


def create_app():
    app = Flask(__name__)
    cache = ThumbnailCache()
    app.wsgi_app = HTTPMetrics(app.wsgi_app)

    @app.get(f"/api/thumbnails/{VERSION}/<image_id>")
    def thumbnail(image_id):
        try:
            image_id = str(UUID(image_id))
            size = int(request.args.get("size", "256"))
        except ValueError:
            abort(400)
        if size not in SIZES:
            abort(400)
        try:
            found = cache.ensure(image_id, (size,))
        except (InvalidImage, EndpointConnectionError, ConnectionClosedError, ReadTimeoutError, ConnectTimeoutError):
            FALLBACKS.inc()
            log.exception("thumbnail unavailable for %s", image_id)
            response = redirect(f"/api/browse/media/{image_id}", code=302)
            response.headers["Cache-Control"] = "no-store"
            return response
        if found:
            response = redirect(cache.presign(image_id, size), code=302)
            # Expire before the seven-day S3 signature.
            response.headers["Cache-Control"] = "public, max-age=86400, immutable"
            return response
        if not found:
            abort(404)

    return app
